// <auto-generated />
using System;
using CoinMarketCap.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinMarketCap.Service.Migrations
{
    [DbContext(typeof(CoinMarketCapDbContext))]
    partial class CoinMarketCapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoinMarketCap.Service.Infrastructure.Persistence.Entities.CryptoPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConvertCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(38, 8)
                        .HasColumnType("decimal(38,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PercentChange1h")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PercentChange24h")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PercentChange7d")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Price")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Volume24h")
                        .HasPrecision(38, 8)
                        .HasColumnType("decimal(38,8)");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedUtc");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("Symbol", "ConvertCurrency");

                    b.ToTable("CryptoPrices", (string)null);
                });

            modelBuilder.Entity("CoinMarketCap.Service.Infrastructure.Persistence.Entities.CryptoPriceSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PriceSnapshots", (string)null);
                });

            modelBuilder.Entity("CoinMarketCap.Service.Infrastructure.Persistence.Entities.CryptoPriceEntity", b =>
                {
                    b.HasOne("CoinMarketCap.Service.Infrastructure.Persistence.Entities.CryptoPriceSnapshotEntity", "Snapshot")
                        .WithMany("Prices")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("CoinMarketCap.Service.Infrastructure.Persistence.Entities.CryptoPriceSnapshotEntity", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
