// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TcmbRatesWorker.Infrastructure.Persistence;

#nullable disable

namespace TcmbRatesWorker.Migrations
{
    [DbContext(typeof(RatesDbContext))]
    partial class RatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tcmb")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TcmbRatesWorker.Infrastructure.Persistence.Entities.RateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BanknoteBuying")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BanknoteSelling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("ForexBuying")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ForexSelling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RateDate", "CurrencyCode")
                        .IsUnique();

                    b.ToTable("Rates", "tcmb");
                });
#pragma warning restore 612, 618
        }
    }
}
